[package]
name = "ni_frc_sys"
version = "0.1.0"
edition = "2021"
links = "ni_frc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = { workspace = true, features = ["parallel"] }
