[package]
name = "xtask"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.65.1"
dirs = "5.0.0"
ureq = "2.6.2"
walkdir = "2.3.3"
zip = "0.6.4"
