[package]
name = "toy_robot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal-async = "1.0.0"
frc = { path = "../frc" }
tokio = { version = "1.35.0", features = ["full"] }
